export const GET_AUTHORS="GET_AUTHORS";
export const GET_SELECTED_AUTHOR ="GET_SELECTED_AUTHOR";
export const GET_SELECTED_POST ="GET_SELECTED_POST";
export const GET_AUTHORS_POSTS = "GET_AUTHORS_POSTS";
export const GET_POSTS_COMMENTS = "GET_POSTS_COMMENTS";
export const GET_TOP_LIKED_POST ="GET_TOP_LIKED_POST"